import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext(null);

export const TRANSLATIONS = {
  mr: {
    // Navigation & Common
    mandalName: 'श्री बाल गणेश मंडळ धानोरा बु.',
    year: '२०२६',
    sacredMantra: '॥ ॐ गं गणपतये नमः ॥',
    home: 'मुख्य पृष्ठ',
    homeShort: 'दर्शन',
    liveBoard: 'थेट देणगी फलक',
    liveBoardShort: 'थेट फलक',
    volunteerDesk: 'स्वयंसेवक कक्ष',
    volunteerShort: 'स्वयंसेवक',
    adminDesk: 'व्यवस्थापक कक्ष',
    adminShort: 'व्यवस्थापक',
    login: 'लॉगिन',
    logout: 'बाहेर पडा',
    ringBell: 'घंटी',
    liveSync: 'Live',
    bhakti: 'भक्ती',
    footerShloka: '॥ मोरया रे बाप्पा मोरया रे, गणपती बाप्पा मोरया, मंगलमूर्ती मोरया ॥',
    trustNotice: 'श्री बाल गणेश मंडळ धानोरा बु. ट्रस्ट • नोंदणी क्र. महा/२०२६/गणेश-१',
    langToggleLabel: 'Language / भाषा',
    refresh: 'रिफ्रेश',
    save: 'सेव्ह करा',
    saving: 'सेव्ह होत आहे...',
    cancel: 'रद्द करा',
    delete: 'हटवा',
    deleting: 'हटवत आहे...',
    edit: 'संपादित करा',
    close: 'बंद करा',
    search: 'शोधा',
    all: 'सर्व',
    actions: 'क्रिया',
    time: 'वेळ',
    amount: 'रक्कम',
    donor: 'भाविक',
    phone: 'मोबाईल',
    city: 'गाव / शहर',
    category: 'सेवा प्रकार',
    status: 'स्थिती',
    active: 'सक्रिय',
    inactive: 'निष्क्रिय',
    superAdmin: 'मुख्य प्रशासक',
    volunteer: 'स्वयंसेवक',
    admin: 'व्यवस्थापक',
    cash: 'रोख (Cash)',
    online: 'ऑनलाइन (Online)',
    total: 'एकूण',
    loading: 'लोड होत आहे...',
    justNow: 'आत्ताच',
    newBadge: 'नवीन!',
    confirmDelete: 'खरोखर हटवायचे आहे का?',
    saveSuccess: 'बदल यशस्वीरित्या सेव्ह झाले!',
    error: 'त्रुटी आली',

    // Hero Section
    heroBadge: 'विघ्नहर्ता • सुखकर्ता • सर्वमंगलकारक',
    heroTitle: '॥ श्री गणेशाय नमः ॥',
    heroSubtitle: 'श्री बाल गणेश मंडळ धानोरा बु. मध्ये आपले सहर्ष स्वागत! बाप्पाच्या चरणी नतमस्तक होऊन सुख, शांती आणि समृद्धीचे शुभाशीर्वाद प्राप्त करा.',
    showerFlowers: '🌸 पुष्पवृष्टी करा (Shower Flowers)',
    lightDiya: '🪔 दीप प्रज्वलित करा',
    diyaLit: '🪔 नंदादीप तेवत आहे',
    flowerChimeMsg: 'पुष्पवृष्टी समर्पित झाली! बाप्पा मोरया! 🌸',
    diyaLitMsg: '॥ शुभं करोति कल्याणम् आरोग्यं धनसंपदा ॥ दीप प्रज्वलित झाला! 🪔',
    btnLiveBoard: 'पहा थेट देणगी फलक (Live Board)',
    btnVolunteerDesk: 'स्वयंसेवक कक्ष (Volunteer Desk)',
    prevDarshan: 'मागील दर्शन',
    nextDarshan: 'पुढील दर्शन',
    darshanProgress: 'दर्शन',
    footerQuote: '॥ मोरया रे बाप्पा मोरया रे, पुढच्या वर्षी लवकर या ॥',

    // Ashtavinayak Section
    ashtavinayakBadge: 'महाराष्ट्राची कुलदैवते',
    ashtavinayakTitle: 'पवित्र अष्टविनायक यात्रा दर्शन (Eight Sacred Shrines)',
    ashtavinayakSubtitle: 'स्वयंभू प्रकट झालेल्या ८ पवित्र श्री गणेशांच्या मंदिरांचा इतिहास, वैशिष्ट्ये आणि महिमा.',
    shrineBadge: 'तीर्थक्षेत्र',
    readDetails: 'माहिती वाचा',
    ashtavinayakModalTitle: 'अष्टविनायक तीर्थक्षेत्र दर्शन',
    templeGlory: 'महिमा व कथा:',
    templeSpecial: 'विशेष वैशिष्ट्ये:',
    bappaMoryaClose: 'बाप्पा मोरया! (Close)',

    // Symbolism Section
    symbolismBadge: 'आध्यात्मिक तत्त्वज्ञान',
    symbolismTitle: 'गणपती बाप्पाच्या रूपाचे गूढ रहस्य (Divine Symbolism)',
    symbolismSubtitle: 'श्री गणेशाचे प्रत्येक अंग जीवनात यशस्वी, सुखी आणि आनंदी होण्याचा आदर्श जीवनमंत्र शिकवते.',

    // Utsav Schedule Section
    scheduleBadge: 'उत्सव दिनदर्शिका',
    scheduleTitle: 'दैनिक आरत्या व १० दिवसीय कार्यक्रम वेळापत्रक',
    scheduleSubtitle: 'श्री गणेशोत्सव काळातील दररोजच्या आरत्या, महाप्रसाद आणि विशेष सांस्कृतिक कार्यक्रमांचे संपूर्ण वेळापत्रक.',
    dailyScheduleTitle: 'दैनिक नित्य आरत्या व महाप्रसाद वेळा',
    specialEventsTitle: '१० दिवसांचे विशेष उत्सव व सांस्कृतिक सोहळे',
    editScheduleBtn: 'वेळापत्रक संपादित करा (Admin)',
    sacredOfferingsTitle: 'नैवेद्य व पूजन माहिती',
    modakTitle: '२१ मोदकांचा प्रसाद',
    modakDesc: 'उकडीचे किंवा तळलेले २१ मोदक बाप्पाला अत्यंत प्रिय आहेत. यामुळे तृप्ती आणि मनाची एकाग्रता वाढते.',
    durvaTitle: '२१ दुर्वांची जोडी',
    durvaDesc: 'अनलासुर राक्षसाचा दाह शांत करण्यासाठी दुर्वा अर्पण केल्या जातात. दुर्वा ही शरीरातील उष्णता शांत करण्याचे प्रतीक आहे.',
    jaswandTitle: 'लाल जास्वंदीचे फूल',
    jaswandDesc: 'लाल रंग हा तेज, ऊर्जा आणि चैतन्याचा कारक आहे. गणपती बाप्पाच्या मस्तकावर लाल जास्वंद अर्पण करणे अत्यंत शुभ मानले जाते.',
    adminScheduleModalTitle: 'दैनिक आरत्या व महाप्रसाद वेळापत्रक संपादन (Admin Only)',
    adminScheduleModalSub: 'येथे केलेले बदल थेट मुख्य पृष्ठावर सर्व भाविकांना दिसतील.',
    scheduleSavedMsg: '✅ दैनिक आरत्या व महाप्रसाद वेळापत्रक यशस्वीरित्या सेव्ह झाले!',
    addAartiBtn: '+ नवीन आरती / वेळ जोडा',
    saveScheduleBtn: 'बदल सेव्ह करा व Live करा',

    // Social Initiatives Section
    initiativesBadge: 'सामाजिक व धार्मिक उपक्रम',
    initiativesTitle: 'मंडळाचे सामाजिक उपक्रम (Initiatives Funded by Seva)',
    initiativesSubtitle: 'आपल्या वर्गणी व देणगीतून साकारलेली लोकोपयोगी कार्ये',
    editInitiativesBtn: 'उपक्रम संपादित करा (Admin)',
    adminInitiativesModalTitle: 'सामाजिक उपक्रम संपादन (Admin Only)',
    adminInitiativesModalSub: 'येथे केलेले बदल मुख्य पृष्ठावर त्वरित थेट लागू होतील.',
    initiativesSavedMsg: '✅ सामाजिक उपक्रम यशस्वीरित्या सेव्ह झाले!',
    addInitiativeBtn: '+ नवीन उपक्रम जोडा (Add New)',
    saveInitiativesBtn: 'बदल सेव्ह करा',

    // Dakshina Board
    dakshinaTitle: 'थेट देणगी व पारदर्शकता फलक (Live Display Board)',
    dakshinaSubtitle: 'पंडाल मुख्य स्क्रीन व टीव्ही डिस्प्लेसाठी थेट अद्यतन',
    scanPayTitle: 'Scan & Pay Dakshina',
    scanPaySubtitle: 'कोणत्याही अधिकृत UPI ॲपद्वारे स्कॅन करून सेवा अर्पण करा',
    openMobileUpi: '📱 मोबाईलवर थेट UPI ॲप उघडा',
    upiLimitNote: 'टीप: काही ॲप्समध्ये मर्यादा एरर येत असल्यास वरील UPI ID कॉपी करून थेट ॲपमध्ये "Pay to UPI ID" द्वारे पेमेंट करा.',
    npciCompliantNotice: 'अधिकृत NPCI UPI प्रणाली (P2P Direct)',
    copyUpi: 'Copy',
    copiedUpi: 'Copied!',
    safeAccountNotice: 'सुरक्षित व अधिकृत मंडळ बँक खाते',
    exitFullscreen: 'Exit Fullscreen',
    enterFullscreen: 'फुलस्क्रीन (TV Mode)',
    digitalSevaBadge: 'डिजिटल सेवा अर्पण',
    verifyPaymentBtn: '🔔 मी ऑनलाइन पैसे भरले आहेत (पावती विनंती करा)',
    verifyModalBadge: 'ऑनलाइन देणगी पडताळणी',
    verifyModalTitle: 'पेमेंट पडताळणी विनंती (Verify Payment)',
    verifyModalSub: 'आपण केलेल्या UPI पेमेंटचा तपशील पाठवा. व्यवस्थापकांच्या पडताळणीनंतर पावती तयार होईल.',
    verifySuccessMsg: 'पडताळणी विनंती यशस्वीपणे पाठवली!',
    verifySuccessSub: 'आपली सेवा बाप्पाच्या चरणी लवकरच डॅशबोर्ड व स्क्रीनवर जोडली जाईल!',
    verifyDoneBtn: 'पूर्ण झाले (Close)',
    verifyNameLabel: 'भाविकांचे नाव (Donor Name) *',
    verifyNamePlaceholder: 'उदा. श्री. सचिन रमेश पाटील',
    verifyAmountLabel: 'दिलेली रक्कम (Amount Paid in ₹) *',
    verifyAmountPlaceholder: 'उदा. 1100',
    verifyUtrLabel: 'UPI ट्रॅन्झॅक्शन / UTR नंबर *',
    verifyUtrPlaceholder: 'उदा. 12 अंकी UTR किंवा Bank Ref. No.',
    verifyUtrHint: 'आपल्या GPay / PhonePe / Paytm वरील पेमेंट पावतीतील UTR नंबर टाका.',
    verifyPhoneLabel: 'मोबाईल नंबर',
    verifyPhonePlaceholder: '१० अंकी नंबर',
    verifyCityLabel: 'गाव / शहर',
    verifyCityPlaceholder: 'उदा. मुंबई, पुणे',
    verifyCategoryLabel: 'सेवा प्रकार',
    verifySubmitBtn: 'पडताळणीसाठी पाठवा (Submit Verification)',
    verifySubmittingBtn: 'पडताळणी विनंती पाठवत आहे...',
    enterValidName: 'कृपया आपले नाव प्रविष्ट करा.',
    enterValidAmount: 'कृपया वैध देणगी रक्कम प्रविष्ट करा.',
    enterValidUtr: 'कृपया UPI Transaction ID / 12 अंकी UTR नंबर प्रविष्ट करा.',

    // Total Counter & Metrics
    totalCollectionBadge: '🌺 एकूण जमा सेवा निधी (Live Seva Collection)',
    targetGoal: 'लक्ष्य (Target):',
    targetGoalPurpose: 'महाप्रसाद, मंडप सजावट व विसर्जन सोहळ्यासाठी',
    campaignProgress: 'ध्येय प्रगती (Progress)',
    remaining: 'शिल्लक',
    nearingGoal: 'उद्दिष्ट पूर्ततेच्या जवळ!',
    statusLabel: 'सद्यस्थिती:',
    achievedLabel: 'पूर्ण',
    finalGoalLabel: 'अंतिम उद्दिष्ट:',
    totalDonorsTitle: 'एकूण भाविक (Total Donors)',
    activeDonorsBadge: 'सक्रिय सहभागी',
    mealsServedTitle: 'महाप्रसाद सेवा (Meals Served)',
    annadaanBadge: 'अन्नदान सेवा',
    platesSuffix: ' थाळ्या',
    aartiSponsorsTitle: 'आरती प्रायोजक (Aarti Sevadars)',
    dailyAartiBadge: 'दैनिक आरती',
    hostsSuffix: ' यजमान',

    // Recent Donors List
    recentDonorsTitle: 'थेट देणगीदार व सेवा यादी (Live Donors List)',
    recentDonorsSub: 'गणपती बाप्पाच्या चरणी अर्पण केलेल्या सेवांचे थेट अद्यतन (Real-time Live Updates)',
    devoteesCountSuffix: 'भाविक',
    searchDonorsPlaceholder: 'नाव किंवा शहर शोधा...',
    allDonorsTab: 'सर्व देणगीदार (All)',
    prasadSevaTab: 'महाप्रसाद सेवा',
    aartiDeepTab: 'आरती / दीप सेवा',
    vipSevaTab: 'विशेष सेवा (>₹१०,०००)',
    noDonorsFound: 'कोणतेही देणगीदार आढळले नाहीत (No donors matched your search)',
    deleteDonationTitle: 'व्यवस्थापक: ही देणगी हटवा (Delete Donation)',
    deleteConfirmTitle: '⚠️ प्रशासक क्रिया: खरोखर देणगी हटवायची आहे का?',

    // Scrolling Ticker
    tickerLiveBadge: 'लाईव्ह सूचना',
    tickerLivePrefix: 'लाईव्ह देणगी:',

    // Volunteer Form & Desk
    volunteerDeskTitle: 'स्वयंसेवक कक्ष (Volunteer Desk)',
    volunteerDeskSub: 'कॅश व ऑनलाइन देणग्यांची थेट नोंदणी कक्ष',
    authorizedAccessBadge: 'अधिकृत प्रवेश 🟢',
    onDutyBadge: 'कार्यरत स्वयंसेवक',
    sessionEntriesBadge: 'नोंदणीकृत पावत्या (Receipts)',
    sessionTotalBadge: 'एकूण जमा सेवा निधी (Live)',
    recorderBadge: 'नोंदणीकर्ता',
    formTitle: 'देणगी नोंदणी फॉर्म',
    formSub: 'कॅश किंवा ऑनलाइन पावती तात्काळ नोंदवा (MongoDB & Live TV Sync)',
    mobileCounterBadge: '📱 स्वयंसेवक मोबाईल काऊंटर',
    paymentMethod: 'पेमेंट पद्धत (Payment Method)',
    onlineUpi: 'ऑनलाइन (UPI / QR)',
    donorNameLabel: 'भाविकांचे नाव (Donor Name) *',
    donorNamePlaceholder: 'उदा. श्री. सचिन रमेश पाटील किंवा सहपरिवार',
    amountLabel: 'देणगी रक्कम (Amount in ₹) *',
    amountPlaceholder: 'उदा. 1100',
    sevaTypeLabel: 'सेवा प्रकार (Seva Category)',
    cityLabel: 'गाव / शहर (Locality / City)',
    cityPlaceholder: 'उदा. दादर, मुंबई, पुणे',
    phoneLabel: 'मोबाईल क्र. (WhatsApp पावतीसाठी)',
    phonePlaceholder: '१० अंकी मोबाईल नंबर',
    submitDonationBtn: 'पावती तयार करा व देणगी नोंदवा',
    submitting: 'नोंद होत आहे...',
    whatsappShareBtn: 'WhatsApp वर पावती पाठवा',
    newReceiptBtn: 'नवीन नोंदणी',
    receiptGenerated: 'पावती तयार झाली (Receipt Generated)',
    sessionHistoryTitle: 'नोंदणीकृत देणगी इतिहास (Live Donation Records)',
    viewReceiptBtn: 'पावती पहा (Receipt)',
    allReceiptsFilter: 'सर्व पावत्या',
    myShiftFilter: 'माझ्या शिफ्टमधील',
    searchReceiptPlaceholder: 'नाव, फोन, पावती क्र. किंवा शहराने शोधा...',
    receiptCol: 'पावती क्र.',
    donorCol: 'भाविकांचे नाव',
    sevaCol: 'सेवा प्रकार',
    recorderCol: 'नोंदणीकर्ता',
    amountCol: 'रक्कम (₹)',
    timeCol: 'वेळ',
    actionCol: 'क्रिया',
    noDonationsYet: 'या सत्रात अद्याप कोणतीही देणगी नोंदवली गेलेली नाही. वरील फॉर्म वापरून पहिली देणगी नोंदवा.',

    // Admin Page
    adminTitle: 'मुख्य व्यवस्थापक नियंत्रण कक्ष (Admin Panel)',
    adminSub: 'QR कोड संपादन, देणगी ध्येय मर्यादा, ऑनलाइन पेमेंट पडताळणी व स्वयंसेवक व्यवस्थापन',
    liveTvScreenBtn: '📺 Live TV स्क्रीन',
    refreshBtn: 'रिफ्रेश',
    tabVerification: 'ऑनलाइन पेमेंट पडताळणी',
    tabSettings: 'ध्येय रक्कम & QR कोड सेटिंग्ज',
    tabNotices: 'सूचना फलक (Notice Board)',
    tabUsers: 'स्वयंसेवक कक्ष व्यवस्थापन',
    tabDonations: 'देणग्या व्यवस्थापन व हटवा',
    newRequestsBadge: 'नवीन',
    zeroPendingBadge: '० प्रलंबित',
    pendingRequestsTitle: 'प्रलंबित विनंत्या',
    verificationSectionTitle: 'ऑनलाइन देणगी पडताळणी विनंत्या',
    verificationSectionSub: 'भाविकांनी QR कोड स्कॅन करून पाठवलेल्या UTR नंबरची खात्री करून एका क्लिकवर पावती मंजूर करा.',
    allCheckedMsg: 'सर्व ऑनलाइन पेमेंट तपासणी पूर्ण झाली आहे!',
    noPendingMsg: 'सध्या कोणतीही नवीन ऑनलाइन देणगी पडताळणी प्रलंबित नाही. नवीन भाविकाने QR कोडवरून देणगी भरल्यास येथे त्वरित दिसेल.',
    approveBtn: '✅ मंजूर करा (Approve)',
    rejectBtn: 'नाकार / रद्द करा',
    checkingBtn: 'तपासत आहे...',
    targetSettingsTitle: 'उत्सव ध्येय रक्कम व QR कोड संपादन',
    targetSettingsSub: 'येथे बदल केलेल्या सेटिंग्ज थेट Live TV स्क्रीन व मोबाईल डॅशबोर्डवर तात्काळ दिसतील.',
    targetLimitLabel: '🎯 एकूण देणगी ध्येय मर्यादा (Target Collection Limit in ₹) *',
    targetLimitHint: 'डॅशबोर्ड प्रगती पट्टी (Progress Bar) व TV स्क्रीनवरील लक्ष्य रक्कम येथे बदलते.',
    upiIdLabel: '📱 मंडळाचा अधिकृत UPI ID (Official UPI ID) *',
    mandalNameLabel: '🏛️ मंडळाचे / बँक खात्याचे नाव (Mandal Name)',
    customQrLabel: '🖼️ कस्टम QR कोड इमेज URL (Custom QR Image Link - Optional)',
    customQrHint: 'टीप: जर आपल्याकडे बँकेचा / PhonePe / Paytm चा मूळ QR फोटो असेल, तर त्याची लिंक येथे टाका. रिकामे ठेवल्यास सिस्टीम आपोआप हाय-स्पीड QR तयार करते!',
    qrNoteLabel: '📝 QR कोड सूचना / नोट (QR Note)',
    ganeshaPhotosLabel: '🪔 मुख्य पृष्ठावरील गणेश छायाचित्रे (Cloudinary Image Links - Every 5s Slider)',
    ganeshaPhotosHint: 'Cloudinary वर अपलोड केलेल्या प्रत्येक फोटोची लिंक स्वतंत्र ओळीवर (New Line) टाका. मुख्य पृष्ठावर दर ५ सेकंदांनी फोटो आपोआप बदलतील!',
    savePublishBtn: 'सेटिंग्ज सेव्ह करा व Live TV वर लागू करा (Save & Publish)',
    previewTitle: 'भाविकांना दिसणारा QR कोड',
    shortcutsTitle: '✨ मुख्य पृष्ठावरील थेट संपादन (Quick Shortcuts):',
    shortcutsSub: 'तुम्ही Admin म्हणून लॉगिन असल्याने मुख्य पृष्ठावर (Home) थेट "संपादित करा" बटनांवर क्लिक करून बदल करू शकता:',
    goToHome: 'मुख्य पृष्ठावर जा ↗',
    addUserTitle: 'नवीन सदस्य जोडा (Add Volunteer)',
    addUserSub: 'स्वयंसेवक किंवा व्यवस्थापकाचे अधिकृत खाते तयार करा',
    fullNameLabel: 'पूर्ण नाव (Full Name) *',
    fullNamePlaceholder: 'उदा. राहुल सचिन मोरे',
    usernameLabel: 'वापरकर्ता नाव (Username) *',
    usernamePlaceholder: 'उदा. rahul123 किंवा volunteer_dadar',
    passwordLabel: 'पासवर्ड (Password) *',
    passwordPlaceholder: 'किमान ४ अक्षरे / आकडे',
    roleLabel: 'भूमिका (Role & Permissions)',
    roleVolunteer: '🚩 स्वयंसेवक (Volunteer)',
    roleAdmin: '👑 व्यवस्थापक (Admin)',
    addUserBtn: 'सदस्य खात्याची नोंद करा (Save)',
    addingUserBtn: 'जोडत आहे...',
    teamDirectoryTitle: 'नोंदणीकृत सदस्य यादी (Authorized Team)',
    teamDirectorySub: 'सक्रिय / निष्क्रिय करा किंवा आवश्यकतेनुसार खाते हटवा',
    searchUsersPlaceholder: 'नाव किंवा युझरनेम शोधा...',
    noUsersFound: 'कोणताही वापरकर्ता आढळला नाही.',
    statusActiveBtn: 'सुरू',
    statusInactiveBtn: 'बंद',
    mainAdminNotice: '(मुख्य व्यवस्थापक)',
    totalDonationsStat: 'एकूण देणग्या',
    totalCollectionStat: 'एकूण जमा रक्कम',
    cashStat: '💵 रोख रक्कम (Cash)',
    onlineStat: '📱 ऑनलाइन (Online)',
    donationsListTitle: 'सर्व देणग्यांची यादी व थेट व्यवस्थापन (Live Donations List)',
    donationsListSub: 'चुकीची किंवा दुबार देणगी नोंद असल्यास केवळ मुख्य व्यवस्थापक (Admin) येथून कायमस्वरूपी हटवू शकतात.',
    searchDonationsPlaceholder: 'नाव, शहर, फोन किंवा पावती शोधा...',
    filterAll: 'सर्व देणग्या',
    filterCash: '💵 रोख (Cash)',
    filterOnline: '📱 ऑनलाइन (Online)',
    filterHigh: '🌟 विशेष (>₹५,०००)',
    colDonor: 'भाविक (Donor)',
    colAmount: 'रक्कम (Amount)',
    colCategory: 'सेवा वर्ग (Category)',
    colMethod: 'पद्धत (Method)',
    colRecordedBy: 'नोंदणीकर्ता',
    colTime: 'वेळ (Time)',
    colAction: 'क्रिया (Admin Action)',
    noDonationsFound: 'कोणतीही देणगी नोंद आढळली नाही.',

    // Login Page
    loginHeaderTitle: 'मंडळ कक्ष प्रवेश',
    loginHeaderSub: 'स्वयंसेवक व व्यवस्थापकांसाठी अधिकृत प्रवेशद्वार',
    loginBtn: 'प्रवेश करा (Sign In)',
    verifyingLogin: 'पडताळणी सुरू आहे...',
    backToHome: 'मुख्य पृष्ठावर परत जा',
    usernameLoginLabel: 'वापरकर्ता नाव (Username / ID)',
    usernameLoginPlaceholder: 'उदा. admin किंवा volunteer1',
    passwordLoginLabel: 'पासवर्ड (Password)',
    loginEmptyError: 'कृपया वापरकर्ता नाव आणि पासवर्ड प्रविष्ट करा.',
    loginFailedError: 'लॉगिन अयशस्वी झाले. कृपया तपशील तपासा.',
    loginBlockedTitle: '🛡️ सुरक्षा लॉकआउट: IP ब्लॉक केला आहे',
    loginBlockedSub: '१० चुकीच्या पासवर्ड प्रयत्नांमुळे हा IP पुढील ३० मिनिटांसाठी ब्लॉक केला आहे.',
    loginBlockedTimeRemaining: 'पुन्हा प्रयत्न करण्यासाठी शिल्लक वेळ:',
    minutesSuffix: 'मिनिटे',
    secondsSuffix: 'सेकंद',
    securityLockoutNotice: 'सुरक्षा सूचना: अनधिकृत प्रवेश रोखण्यासाठी हा IP तात्पुरता ब्लॉक केला आहे. कृपया ३० मिनिटांनंतर पुन्हा प्रयत्न करा.',
    attemptsRemainingWarning: 'उर्वरित प्रयत्न',
    tabSecurity: '🛡️ सुरक्षा व ब्लॉक केलेले IP',
    blockedIpsTitle: 'सुरक्षा व्यवस्थापन: ब्लॉक केलेले IP पत्ते (Blocked IPs)',
    blockedIpsSub: '१० पेक्षा जास्त चुकीचे पासवर्ड टाकल्यामुळे ३० मिनिटांसाठी ब्लॉक झालेले IP पत्ते.',
    noBlockedIps: 'सध्या कोणताही IP पत्ता ब्लॉक केलेला नाही. सर्व सुरळीत चालू आहे.',
    unblockBtn: 'अनब्लॉक करा (Unblock)',
    unblocking: 'अनब्लॉक होत आहे...',
    ipAddress: 'IP पत्ता',
    blockedUntilLabel: 'ब्लॉक समाप्त वेळ',
    failedCountLabel: 'चुकीचे प्रयत्न',
    lastAttemptLabel: 'शेवटचा प्रयत्न',

    // Aarti Reader
    aartiSectionBadge: '📖 आरती व स्तोत्र संग्रह',
    aartiSectionTitle: 'श्री गणेश आरती, स्तोत्र व प्रार्थना',
    aartiSectionSub: 'घरी किंवा सार्वजनिक मंडळात आरतीच्या वेळी सहज वाचण्यासाठी',
    fontSizeLabel: 'अक्षर आकार:',
    ringBellBtn: 'घंटी वाजवा',

    // Notice Board
    noticeBoardBadge: 'अधिकृत सूचना फलक',
    noticeBoardTitle: 'श्री बाल गणेश मंडळ - सूचना फलक',
    noticeBoardSubtitle: 'आरती, महाप्रसाद, सांस्कृतिक कार्यक्रम व महत्त्वाच्या सूचनांचे थेट अपडेट्स',
    allNotices: 'सर्व सूचना',
    urgentNotices: 'महत्त्वाच्या सूचना',
    eventNotices: 'कार्यक्रम व उत्सव',
    prasadNotices: 'महाप्रसाद व आरती',
    noNoticesYet: 'सध्या कोणतीही नवीन सूचना नाही.',
    postedOn: 'प्रकाशित',
    byAdmin: 'मंडळ व्यवस्थापन',
    addNewNotice: 'नवीन सूचना द्या',
    editNotice: 'सूचना संपादित करा',
    deleteNotice: 'सूचना हटवा',
    noticeTitleLabel: 'सूचनेचे शीर्षक *',
    noticeContentLabel: 'सूचनेचा तपशील *',
    noticeCategoryLabel: 'प्रकार / वर्गवारी',
    noticePriorityLabel: 'प्राधान्य (Priority)',
    catGeneral: 'सर्वसाधारण सूचना 📢',
    catUrgent: 'अत्यंत महत्त्वाची सूचना 🔴',
    catEvent: 'कार्यक्रम व उत्सव 🪔',
    catPrasad: 'महाप्रसाद व अन्नदान 🍲',
    catAarti: 'आरती व दर्शन 🔔',
    priorityNormal: 'सामान्य (Normal)',
    priorityMedium: 'मध्यम (Medium)',
    priorityHigh: 'उच्च (High)',
    publishNoticeBtn: 'सूचना प्रकाशित करा 🚀',
    updateNoticeBtn: 'बदल सेव्ह करा',
    toggleNoticeStatus: 'स्थिती बदला',
    activeNotice: 'सक्रिय (Live)',
    inactiveNotice: 'अप्रकाशित / बंद (Hidden)',
    noticePublishedSuccess: 'सूचना यशस्वीपणे फलकावर प्रकाशित झाली!',
    noticeUpdatedSuccess: 'सूचना अद्ययावत झाली!',
    noticeDeletedSuccess: 'सूचना यशस्वीरित्या हटवली!',
    activeNoticesCount: 'सक्रिय सूचना',
    totalNoticesCount: 'एकूण सूचना',

    // Music & Bhajan Portal
    music: 'भक्ती संगीत',
    musicShort: 'संगीत',
    musicTitle: 'श्री गणेश भक्ती संगीत व गाणी',
    catMusicAll: 'सर्व गाणी (All Songs)',
    catMusicAagman: 'आगमन, ढोल-ताशा व जल्लोष 🥁',
    catMusicBhajan: 'अमर मराठी क्लासिक्स व लोकगीते 🪔',
    catMusicAarti: 'आरती, स्तुती व नित्य प्रार्थना 🔔',
    catMusicSuggestions: 'भाविकांनी सुचवलेली गाणी 👥',
    suggestSongBtn: 'गाणे सुचवा (Suggest Song)',
    suggestSongTitle: 'बाप्पासाठी आवडते गाणे सुचवा',
    suggestSongSubtitle: 'आपले आवडते गणेशगीत मंडळाच्या अधिकृत प्लेलिस्टमध्ये समाविष्ट करण्यासाठी माहिती व YouTube लिंक पाठवा',
    songTitleLabel: 'गाण्याचे नाव / Title *',
    songTitlePlaceholder: 'उदा. देवा श्री गणेशा किंवा सुखकर्ता दुःखहर्ता',
    singerLabel: 'गायक / कलाकार (Singer)',
    singerPlaceholder: 'उदा. अजय-अतुल / सुरेश वाडकर',
    songCategoryLabel: 'गाण्याचा प्रकार (Category)',
    youtubeUrlLabel: 'YouTube व्हिडिओ लिंक किंवा Video ID *',
    youtubeUrlPlaceholder: 'उदा. https://youtu.be/... किंवा https://www.youtube.com/watch?v=...',
    suggestedByLabel: 'आपले नाव (Your Name)',
    suggestedByPlaceholder: 'उदा. राहुल कदम (धानोरा बु.)',
    messageLabel: 'निरोप / विशेष समर्पण (Dedication Note)',
    messagePlaceholder: 'उदा. आगमन मिरवणुकीत वाजवण्यासाठी किंवा बाप्पाच्या सेवेत समर्पित',
    submitSongBtn: 'गाणे मंडळाला सुचवा 🚀',
    submittingSong: 'गाणे जोडले जात आहे...',
    songSubmittedSuccess: 'गाणे यशस्वीरित्या सुचवले गेले व प्लेअरमध्ये जोडले गेले! बाप्पा मोरया! 🎶',
    nowPlaying: 'आता वाजत आहे',
    playSong: 'प्ले करा',
    pauseSong: 'थांबवा',
    openInYoutube: 'YouTube वर पहा',
    shareSong: 'शेअर करा',
    songShared: 'लिंक कॉपी केली!',
    searchSongsPlaceholder: 'गाणे, गायक किंवा प्रकार शोधा...',
    suggestedByDevotee: 'सुचवणारे:',
    noSongsFound: 'या प्रकारात सध्या कोणतेही गाणे उपलब्ध नाही.',
    likeSong: 'आवडले',
    likedSong: 'आवडले!',
    tabMusic: '🎶 भक्ती संगीत',
    adminMusicTitle: 'भाविकांच्या गाण्यांच्या सूचना व्यवस्थापन (Music Suggestions)',
    adminMusicSub: 'भाविकांनी सुचवलेली गाणी तपासा, मंजूर किंवा हटवा',
  },

  en: {
    // Navigation & Common
    mandalName: 'Shri Baal Ganesh Mandal Dhanora Bk.',
    year: '2026',
    sacredMantra: '|| Om Gam Ganapataye Namah ||',
    home: 'Home',
    homeShort: 'Home',
    liveBoard: 'Live Dakshina Board',
    liveBoardShort: 'Live Board',
    volunteerDesk: 'Volunteer Desk',
    volunteerShort: 'Volunteer',
    adminDesk: 'Admin Portal',
    adminShort: 'Admin',
    login: 'Login',
    logout: 'Sign Out',
    ringBell: 'Bell',
    liveSync: 'Live',
    bhakti: 'Devotion',
    footerShloka: '|| Morya Re Bappa Morya Re, Ganpati Bappa Morya, Mangal Murti Morya ||',
    trustNotice: 'Shri Baal Ganesh Mandal Dhanora Bk. Trust • Reg. No. MAH/2026/GANESH-1',
    langToggleLabel: 'Language / भाषा',
    refresh: 'Refresh',
    save: 'Save Changes',
    saving: 'Saving...',
    cancel: 'Cancel',
    delete: 'Delete',
    deleting: 'Deleting...',
    edit: 'Edit',
    close: 'Close',
    search: 'Search',
    all: 'All',
    actions: 'Actions',
    time: 'Time',
    amount: 'Amount',
    donor: 'Donor',
    phone: 'Mobile',
    city: 'City / Locality',
    category: 'Seva Category',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    superAdmin: 'Super Admin',
    volunteer: 'Volunteer',
    admin: 'Admin',
    cash: 'Cash',
    online: 'Online',
    total: 'Total',
    loading: 'Loading...',
    justNow: 'Just now',
    newBadge: 'New!',
    confirmDelete: 'Are you sure you want to delete this?',
    saveSuccess: 'Changes saved successfully!',
    error: 'An error occurred',

    // Hero Section
    heroBadge: 'Remover of Obstacles • Bestower of Joy & Prosperity',
    heroTitle: '|| Shree Ganeshaya Namah ||',
    heroSubtitle: 'Hearty welcome to Shri Baal Ganesh Mandal Dhanora Bk.! Seek the sacred blessings of Lord Ganesha for boundless happiness, peace, and good health.',
    showerFlowers: '🌸 Shower Flowers (पुष्पवृष्टी)',
    lightDiya: '🪔 Light Sacred Diya (दीप प्रज्वलन)',
    diyaLit: '🪔 Sacred Diya is Lit',
    flowerChimeMsg: 'Sacred flowers offered at Lord Ganesha\'s lotus feet! Bappa Morya! 🌸',
    diyaLitMsg: '|| Shubham Karoti Kalyanam || The sacred lamp is glowing bright! 🪔',
    btnLiveBoard: 'View Live Dakshina Board ↗',
    btnVolunteerDesk: 'Volunteer Desk →',
    prevDarshan: 'Previous Darshan',
    nextDarshan: 'Next Darshan',
    darshanProgress: 'Darshan',
    footerQuote: '|| Ganpati Bappa Morya, Pudhchya Varshi Lavkar Ya ||',

    // Ashtavinayak Section
    ashtavinayakBadge: 'Guardian Deities of Maharashtra',
    ashtavinayakTitle: 'Sacred Ashtavinayak Pilgrimage (Eight Holy Shrines)',
    ashtavinayakSubtitle: 'History, spiritual significance, and unique legends of the 8 self-manifested (Swayambhu) Ganesha shrines.',
    shrineBadge: 'Holy Shrine',
    readDetails: 'Read Details',
    ashtavinayakModalTitle: 'Ashtavinayak Sacred Pilgrimage Darshan',
    templeGlory: 'Divine Legend & Significance:',
    templeSpecial: 'Unique Temple Features:',
    bappaMoryaClose: 'Bappa Morya! (Close)',

    // Symbolism Section
    symbolismBadge: 'Spiritual Wisdom',
    symbolismTitle: 'Divine Symbolism of Lord Ganesha',
    symbolismSubtitle: 'Every sacred feature of Lord Ganesha imparts timeless wisdom for living a noble, peaceful, and accomplished life.',

    // Utsav Schedule Section
    scheduleBadge: 'Festival Calendar',
    scheduleTitle: 'Daily Prayers & 10-Day Festival Programme',
    scheduleSubtitle: 'Detailed timetable of daily morning/evening prayers, maha-prasad community feasts, and spiritual celebrations.',
    dailyScheduleTitle: 'Daily Regular Aarti & Maha-Prasad Schedule',
    specialEventsTitle: '10-Day Special Festive Celebrations & Events',
    editScheduleBtn: 'Edit Schedule (Admin)',
    sacredOfferingsTitle: 'Sacred Offerings & Pooja Guidelines',
    modakTitle: '21 Sacred Modaks Offering',
    modakDesc: 'Lord Ganesha dearly cherishes 21 steamed or fried sweet modaks, symbolizing ultimate fulfillment and spiritual wisdom.',
    durvaTitle: '21 Sacred Durva Grass Blades',
    durvaDesc: 'Offered to soothe the divine heat after defeating demon Analasura; symbolizes coolness, endurance, and purity.',
    jaswandTitle: 'Red Hibiscus Blossom',
    jaswandDesc: 'Red radiates vitality, brilliance, and cosmic energy. Offering red hibiscus to Lord Ganesha is profoundly auspicious.',
    adminScheduleModalTitle: 'Edit Daily Aarti & Prasad Schedule (Admin Only)',
    adminScheduleModalSub: 'Modifications made here will instantly be visible live on the home page for all devotees.',
    scheduleSavedMsg: '✅ Daily prayer and prasadam timetable saved successfully!',
    addAartiBtn: '+ Add New Prayer / Session',
    saveScheduleBtn: 'Save Changes & Publish Live',

    // Social Initiatives Section
    initiativesBadge: 'Devotional & Community Outreach',
    initiativesTitle: 'Mandal Social Initiatives (Funded by Seva)',
    initiativesSubtitle: 'Compassionate community welfare activities made possible by your donations and seva',
    editInitiativesBtn: 'Edit Initiatives (Admin)',
    adminInitiativesModalTitle: 'Edit Community Initiatives (Admin Only)',
    adminInitiativesModalSub: 'Changes updated here will instantly reflect live across the home page.',
    initiativesSavedMsg: '✅ Community initiatives saved successfully!',
    addInitiativeBtn: '+ Add New Initiative',
    saveInitiativesBtn: 'Save Changes',

    // Dakshina Board
    dakshinaTitle: 'Live Dakshina & Transparency Display Board',
    dakshinaSubtitle: 'Real-time broadcast sync for pandal televisions and large monitors',
    scanPayTitle: 'Scan & Pay Dakshina',
    scanPaySubtitle: 'Scan & offer devotional contributions via any official UPI app',
    openMobileUpi: '📱 Open UPI App Directly on Mobile',
    upiLimitNote: 'Tip: If an app displays a bank limit error, copy the UPI ID above and pay directly via "Pay to UPI ID".',
    npciCompliantNotice: 'Official NPCI UPI Standard (P2P Direct)',
    copyUpi: 'Copy',
    copiedUpi: 'Copied!',
    safeAccountNotice: 'Verified & Secure Mandal Trust Bank Account',
    exitFullscreen: 'Exit Fullscreen',
    enterFullscreen: 'Fullscreen (TV Mode)',
    digitalSevaBadge: 'Digital Seva Offering',
    verifyPaymentBtn: '🔔 I Have Paid Online (Request Receipt)',
    verifyModalBadge: 'Online Payment Verification',
    verifyModalTitle: 'Payment Verification Request',
    verifyModalSub: 'Submit your UPI payment details. Your official receipt will be generated upon admin review.',
    verifySuccessMsg: 'Verification request submitted successfully!',
    verifySuccessSub: 'Your seva contribution will be added to the live screen upon admin confirmation!',
    verifyDoneBtn: 'Done (Close)',
    verifyNameLabel: 'Devotee / Family Name *',
    verifyNamePlaceholder: 'e.g. Mr. Sachin Ramesh Patil & Family',
    verifyAmountLabel: 'Amount Paid (₹) *',
    verifyAmountPlaceholder: 'e.g. 1100',
    verifyUtrLabel: 'UPI Transaction ID / 12-Digit UTR *',
    verifyUtrPlaceholder: 'e.g. 12-digit UTR or Bank Reference No.',
    verifyUtrHint: 'Found on your GPay / PhonePe / Paytm transaction success receipt.',
    verifyPhoneLabel: 'Mobile Number',
    verifyPhonePlaceholder: '10-digit mobile number',
    verifyCityLabel: 'City / Locality',
    verifyCityPlaceholder: 'e.g. Mumbai, Pune',
    verifyCategoryLabel: 'Seva Category',
    verifySubmitBtn: 'Submit for Verification',
    verifySubmittingBtn: 'Submitting Request...',
    enterValidName: 'Please enter devotee name.',
    enterValidAmount: 'Please enter a valid donation amount.',
    enterValidUtr: 'Please enter your UPI Transaction / 12-digit UTR number.',

    // Total Counter & Metrics
    totalCollectionBadge: '🌺 Total Live Dakshina Collection',
    targetGoal: 'Target Goal:',
    targetGoalPurpose: 'For Maha-Prasad, pandal decoration & grand visarjan',
    campaignProgress: 'Campaign Progress',
    remaining: 'Remaining',
    nearingGoal: 'Nearing Festival Goal!',
    statusLabel: 'Status:',
    achievedLabel: 'Achieved',
    finalGoalLabel: 'Festival Goal:',
    totalDonorsTitle: 'Devotees & Donors',
    activeDonorsBadge: 'Active Donors',
    mealsServedTitle: 'Maha-Prasad Served',
    annadaanBadge: 'Annadaan Seva',
    platesSuffix: ' Plates',
    aartiSponsorsTitle: 'Aarti Sevadars',
    dailyAartiBadge: 'Daily Aarti',
    hostsSuffix: ' Hosts',

    // Recent Donors List
    recentDonorsTitle: 'Live Devotees & Dakshina Feed',
    recentDonorsSub: 'Real-time devotional offerings dedicated at Lord Ganesha\'s lotus feet',
    devoteesCountSuffix: 'Devotees',
    searchDonorsPlaceholder: 'Search by name or city...',
    allDonorsTab: 'All Donors',
    prasadSevaTab: 'Maha-Prasad Seva',
    aartiDeepTab: 'Aarti / Deep Seva',
    vipSevaTab: 'VIP Seva (>₹10,000)',
    noDonorsFound: 'No donor records found matching your search.',
    deleteDonationTitle: 'Admin: Delete this donation record',
    deleteConfirmTitle: '⚠️ Admin Action: Are you sure you want to permanently delete this donation?',

    // Scrolling Ticker
    tickerLiveBadge: 'Live Update',
    tickerLivePrefix: 'Live Dakshina:',

    // Volunteer Form & Desk
    volunteerDeskTitle: 'Volunteer Desk (देणगी नोंदणी)',
    volunteerDeskSub: 'Direct counter for recording cash and online contributions',
    authorizedAccessBadge: 'Authorized Access 🟢',
    onDutyBadge: 'On-Duty Volunteer',
    sessionEntriesBadge: 'Shift Receipts',
    sessionTotalBadge: 'Total Live Collection',
    recorderBadge: 'Logged By',
    formTitle: 'Donation Entry Form',
    formSub: 'Instantly record cash/UPI receipts (Syncs with MongoDB & Live TV)',
    mobileCounterBadge: '📱 Volunteer Mobile Counter',
    paymentMethod: 'Payment Method',
    onlineUpi: 'Online (UPI / QR)',
    donorNameLabel: 'Donor / Family Name *',
    donorNamePlaceholder: 'e.g. Mr. Sachin Ramesh Patil & Family',
    amountLabel: 'Donation Amount (₹) *',
    amountPlaceholder: 'e.g. 1100',
    sevaTypeLabel: 'Seva Category (सेवा प्रकार)',
    cityLabel: 'City / Locality (गाव/शहर)',
    cityPlaceholder: 'e.g. Dadar, Mumbai, Pune',
    phoneLabel: 'Mobile No. (for WhatsApp Receipt)',
    phonePlaceholder: '10-digit mobile number',
    submitDonationBtn: 'Generate Receipt & Log Donation',
    submitting: 'Saving to Database...',
    whatsappShareBtn: 'Share Receipt on WhatsApp',
    newReceiptBtn: 'Record New Donation',
    receiptGenerated: 'Receipt Generated (पावती तयार)',
    sessionHistoryTitle: 'Current Shift Session Records (नोंदणी इतिहास)',
    viewReceiptBtn: 'View Receipt',
    allReceiptsFilter: 'All Receipts',
    myShiftFilter: 'My Shift Only',
    searchReceiptPlaceholder: 'Search by name, phone, receipt #, or locality...',
    receiptCol: 'Receipt #',
    donorCol: 'Donor Name',
    sevaCol: 'Seva Type',
    recorderCol: 'Volunteer',
    amountCol: 'Amount (₹)',
    timeCol: 'Time',
    actionCol: 'Action',
    noDonationsYet: 'No donations have been logged during this shift yet. Use the form above to record the first one.',

    // Admin Page
    adminTitle: 'Admin Management Portal (व्यवस्थापक नियंत्रण)',
    adminSub: 'Manage QR code, target budget, verify online payments & organize team',
    liveTvScreenBtn: '📺 Live TV Screen',
    refreshBtn: 'Refresh',
    tabVerification: 'Online Payment Verification',
    tabSettings: 'Goal Amount & QR Settings',
    tabNotices: 'Notice Board',
    tabUsers: 'Volunteer Team Management',
    tabDonations: 'Donations Management & Delete',
    newRequestsBadge: 'New',
    zeroPendingBadge: '0 Pending',
    pendingRequestsTitle: 'Pending Requests',
    verificationSectionTitle: 'Online Payment Verification Requests',
    verificationSectionSub: 'Verify devotee UPI UTR numbers and approve instant receipts with 1 click.',
    allCheckedMsg: 'All online payment requests have been reviewed!',
    noPendingMsg: 'No pending verification requests at this moment. New devotee submissions will show up here instantly.',
    approveBtn: '✅ Approve Receipt',
    rejectBtn: 'Reject / Dismiss',
    checkingBtn: 'Processing...',
    targetSettingsTitle: 'Festival Target Budget & QR Code Setup',
    targetSettingsSub: 'Settings saved here are broadcasted live to pandal TV monitors and mobile devices.',
    targetLimitLabel: '🎯 Target Collection Limit in ₹ *',
    targetLimitHint: 'Updates the progress bar goal on both the live dashboard and TV display.',
    upiIdLabel: '📱 Mandal Official UPI ID *',
    mandalNameLabel: '🏛️ Mandal / Trust Account Name',
    customQrLabel: '🖼️ Custom QR Code Image URL (Optional)',
    customQrHint: 'Note: If you have an official bank QR image link, paste it here. If left empty, the system generates an instant high-res QR code.',
    qrNoteLabel: '📝 QR Display Note / Subtitle',
    ganeshaPhotosLabel: '🪔 Home Page Deity Photos (Cloudinary URLs - 5s Auto-Slider)',
    ganeshaPhotosHint: 'Paste each Cloudinary photo link on a new line. Images will cycle smoothly every 5 seconds on the home page.',
    savePublishBtn: 'Save Settings & Publish Live',
    previewTitle: 'Devotee-Facing QR Code Preview',
    shortcutsTitle: '✨ Direct Home Page Quick Shortcuts:',
    shortcutsSub: 'Because you are logged in as Admin, you can click "Edit" directly on home page sections:',
    goToHome: 'Go to Section ↗',
    addUserTitle: 'Add Authorized Team Member',
    addUserSub: 'Create an authorized volunteer or administrator account',
    fullNameLabel: 'Full Name *',
    fullNamePlaceholder: 'e.g. Rahul Sachin More',
    usernameLabel: 'Username / Login ID *',
    usernamePlaceholder: 'e.g. rahul123 or volunteer_dadar',
    passwordLabel: 'Password *',
    passwordPlaceholder: 'Minimum 4 characters',
    roleLabel: 'Role & Permissions',
    roleVolunteer: '🚩 Volunteer (Counter Access)',
    roleAdmin: '👑 Administrator (Full Control)',
    addUserBtn: 'Save Member to Database',
    addingUserBtn: 'Saving...',
    teamDirectoryTitle: 'Authorized Team Directory',
    teamDirectorySub: 'Toggle active status or remove user accounts as needed',
    searchUsersPlaceholder: 'Search by name or username...',
    noUsersFound: 'No registered team members found.',
    statusActiveBtn: 'Active',
    statusInactiveBtn: 'Deactivate',
    mainAdminNotice: '(Super Admin)',
    totalDonationsStat: 'Total Receipts',
    totalCollectionStat: 'Total Collection',
    cashStat: '💵 Cash Total',
    onlineStat: '📱 Online Total',
    donationsListTitle: 'Complete Donations Ledger & Records',
    donationsListSub: 'Super administrators can audit records and permanently delete erroneous entries.',
    searchDonationsPlaceholder: 'Search by name, city, phone, or receipt #...',
    filterAll: 'All Donations',
    filterCash: '💵 Cash',
    filterOnline: '📱 Online',
    filterHigh: '🌟 High Value (>₹5,000)',
    colDonor: 'Devotee (Donor)',
    colAmount: 'Amount',
    colCategory: 'Category',
    colMethod: 'Method',
    colRecordedBy: 'Logged By',
    colTime: 'Time',
    colAction: 'Admin Action',
    noDonationsFound: 'No donation entries found.',

    // Login Page
    loginHeaderTitle: 'Portal Login (मंडळ कक्ष प्रवेश)',
    loginHeaderSub: 'Official access gateway for volunteers and administrators',
    demoAccountsTitle: 'Quick 1-Click Demo Accounts:',
    demoAdminBtn: '👑 Main Admin (व्यवस्थापक)',
    demoVolBtn: '🙋‍♂️ Volunteer (स्वयंसेवक)',
    loginBtn: 'Sign In (प्रवेश करा)',
    verifyingLogin: 'Authenticating credentials...',
    backToHome: 'Return to Home Page',
    usernameLoginLabel: 'Username / Login ID',
    usernameLoginPlaceholder: 'e.g. admin or volunteer1',
    passwordLoginLabel: 'Password',
    passwordLoginPlaceholder: 'Enter your secure password',
    loginEmptyError: 'Please enter your username and password.',
    loginFailedError: 'Login failed. Please verify your credentials.',
    loginBlockedTitle: '🛡️ Security Lockout: IP Blocked',
    loginBlockedSub: 'This IP address has been blocked for 30 minutes after 10 failed password attempts.',
    loginBlockedTimeRemaining: 'Time remaining before unlock:',
    minutesSuffix: 'min',
    secondsSuffix: 'sec',
    securityLockoutNotice: 'Security Notice: To prevent unauthorized access, this IP has been temporarily restricted for 30 minutes. Please try again later.',
    attemptsRemainingWarning: 'attempts remaining',
    tabSecurity: '🛡️ Security & Blocked IPs',
    blockedIpsTitle: 'Security Management: Blocked IP Addresses',
    blockedIpsSub: 'IPs locked out for 30 minutes due to 10 consecutive failed password attempts.',
    noBlockedIps: 'No IP addresses are currently blocked. System is secure.',
    unblockBtn: 'Unblock IP',
    unblocking: 'Unblocking...',
    ipAddress: 'IP Address',
    blockedUntilLabel: 'Blocked Until',
    failedCountLabel: 'Failed Attempts',
    lastAttemptLabel: 'Last Attempt',

    // Aarti Reader
    aartiSectionBadge: '📖 Hymns & Prayers Collection',
    aartiSectionTitle: 'Lord Ganesha Aarti, Stotras & Prayers',
    aartiSectionSub: 'Designed for clear and devotional reading at home or in public pandals',
    fontSizeLabel: 'Font Size:',
    ringBellBtn: 'Ring Bell',

    // Notice Board
    noticeBoardBadge: 'Official Notice Board',
    noticeBoardTitle: 'Shri Baal Ganesh Mandal - Notice Board',
    noticeBoardSubtitle: 'Live updates on Aarti, Mahaprasad, cultural programs and mandal announcements',
    allNotices: 'All Notices',
    urgentNotices: 'Urgent',
    eventNotices: 'Programs & Events',
    prasadNotices: 'Prasad & Aarti',
    noNoticesYet: 'No active announcements at the moment.',
    postedOn: 'Posted on',
    byAdmin: 'Mandal Management',
    addNewNotice: 'Post New Notice',
    editNotice: 'Edit Notice',
    deleteNotice: 'Delete Notice',
    noticeTitleLabel: 'Notice Title *',
    noticeContentLabel: 'Notice Details *',
    noticeCategoryLabel: 'Category',
    noticePriorityLabel: 'Priority',
    catGeneral: 'General Announcement 📢',
    catUrgent: 'Urgent / Important 🔴',
    catEvent: 'Programs & Celebrations 🪔',
    catPrasad: 'Maha Prasad & Anna Daan 🍲',
    catAarti: 'Aarti & Darshan 🔔',
    priorityNormal: 'Normal',
    priorityMedium: 'Medium',
    priorityHigh: 'High',
    publishNoticeBtn: 'Publish Announcement 🚀',
    updateNoticeBtn: 'Update Notice',
    toggleNoticeStatus: 'Toggle Status',
    activeNotice: 'Active (Live)',
    inactiveNotice: 'Hidden (Inactive)',
    noticePublishedSuccess: 'Announcement successfully published to Notice Board!',
    noticeUpdatedSuccess: 'Notice updated successfully!',
    noticeDeletedSuccess: 'Notice deleted successfully!',
    activeNoticesCount: 'Active Notices',
    totalNoticesCount: 'Total Notices',

    // Music & Bhajan Portal
    music: 'Bhakti Music',
    musicShort: 'Music',
    musicTitle: 'Shri Ganesh Bhakti Sangeet & Music',
    catMusicAll: 'All Songs',
    catMusicAagman: 'Procession & Dhol Tasha 🥁',
    catMusicBhajan: 'Legendary Classics & Folk 🪔',
    catMusicAarti: 'Soulful Aartis & Prayers 🔔',
    catMusicSuggestions: 'Devotee Suggestions 👥',
    suggestSongBtn: 'Suggest a Song',
    suggestSongTitle: 'Suggest a Ganpati Song',
    suggestSongSubtitle: 'Submit your favorite Ganpati song and YouTube link to feature on the mandal playlist',
    songTitleLabel: 'Song Title *',
    songTitlePlaceholder: 'e.g. Deva Shree Ganesha or Sukhkarta Dukh Harta',
    singerLabel: 'Singer / Artist',
    singerPlaceholder: 'e.g. Ajay-Atul / Suresh Wadkar',
    songCategoryLabel: 'Category',
    youtubeUrlLabel: 'YouTube Video Link or ID *',
    youtubeUrlPlaceholder: 'e.g. https://youtu.be/... or https://www.youtube.com/watch?v=...',
    suggestedByLabel: 'Your Name',
    suggestedByPlaceholder: 'e.g. Rahul Kadam (Dhanora Bk.)',
    messageLabel: 'Dedication / Note',
    messagePlaceholder: 'e.g. For Aagman procession or mandal devotion',
    submitSongBtn: 'Submit Song to Playlist 🚀',
    submittingSong: 'Submitting song...',
    songSubmittedSuccess: 'Song successfully suggested and added to the player! Bappa Morya! 🎶',
    nowPlaying: 'Now Playing',
    playSong: 'Play Song',
    pauseSong: 'Pause',
    openInYoutube: 'Watch on YouTube',
    shareSong: 'Share Song',
    songShared: 'Link copied!',
    searchSongsPlaceholder: 'Search song, singer, or keyword...',
    suggestedByDevotee: 'Suggested by:',
    noSongsFound: 'No songs found in this category.',
    likeSong: 'Like',
    likedSong: 'Liked!',
    tabMusic: '🎶 Bhakti Music',
    adminMusicTitle: 'Devotee Music Suggestions Management',
    adminMusicSub: 'Review, approve, or remove songs suggested by devotees',
  },
};

// =========================================================================
// BILINGUAL DATASETS FOR RICH SECTIONS
// =========================================================================

export const ASHTAVINAYAK_TEMPLES = [
  {
    id: 1,
    name: {
      mr: '१. श्री मयूरेश्वर (श्री क्षेत्र मोरगाव)',
      en: '1. Shri Mayureshwar (Morgaon)',
    },
    district: {
      mr: 'पुणे (कऱ्हा नदीकाठ)',
      en: 'Pune (Karha Riverbank)',
    },
    vahana: {
      mr: 'मयूर (मोर)',
      en: 'Peacock (Mayur)',
    },
    desc: {
      mr: 'अष्टविनायक यात्रेची सुरुवात आणि सांगता मोरगावच्या मयूरेश्वराच्या दर्शनाने होते. कमलासुर दैत्याचा वध करण्यासाठी गणपतीने मोरावर स्वार होऊन हे रूप घेतले होते.',
      en: 'The holy Ashtavinayak pilgrimage traditionally commences and concludes with the darshan of Shri Mayureshwar at Morgaon. Lord Ganesha rode a peacock to vanquish the demon Kamalasura.',
    },
    special: {
      mr: 'या मंदिराची रचना मुघल काळातील किल्ल्यासारखी चारही बाजूंनी उंच तटबंदी असलेली आहे.',
      en: 'The temple architecture resembles a medieval fortress with high stone ramparts and minarets.',
    },
  },
  {
    id: 2,
    name: {
      mr: '२. श्री सिद्धिविनायक (श्री क्षेत्र सिद्धटेक)',
      en: '2. Shri Siddhivinayak (Siddhatek)',
    },
    district: {
      mr: 'अहमदनगर (भीमा नदीकाठ)',
      en: 'Ahmednagar (Bhima Riverbank)',
    },
    vahana: {
      mr: 'सिंह / मूषक',
      en: 'Lion / Mouse',
    },
    desc: {
      mr: 'येथे श्री विष्णूने मधू आणि कैटभ या राक्षसांचा वध करण्यासाठी गणेशाची आराधना करून सिद्धी प्राप्त केली होती. या मूर्तीची सोंड उजवीकडे वळलेली आहे.',
      en: 'Lord Vishnu meditated here on Lord Ganesha to gain divine siddhi before vanquishing the demons Madhu and Kaitabha. The deity features a right-turned trunk (Dakshinabhimukhi).',
    },
    special: {
      mr: 'उजव्या सोंडेचा गणपती कडक शिस्तीचा मानला जातो; येथे प्रदक्षिणेसाठी संपूर्ण डोंगर फिरावे लागते.',
      en: 'A right-trunk Ganesha requires strict observance; completing the temple circumambulation (pradakshina) entails circling the entire hill.',
    },
  },
  {
    id: 3,
    name: {
      mr: '३. श्री बल्लाळेश्वर (श्री क्षेत्र पाली)',
      en: '3. Shri Ballaleshwar (Pali)',
    },
    district: {
      mr: 'रायगड (अंबा नदीकाठ)',
      en: 'Raigad (Amba Riverbank)',
    },
    vahana: {
      mr: 'मूषक',
      en: 'Mouse',
    },
    desc: {
      mr: 'एकमेव मंदिर जे गणेशाच्या निस्सीम भक्त बल्लाळाच्या नावाने ओळखले जाते. भक्ताच्या हाकेला धावून येणारे अत्यंत जागृत देवस्थान.',
      en: 'The only Ganesha shrine named after an ardent devotee—Ballala. Highly revered as a quick-answering (Jagrut) deity who protects faithful devotees.',
    },
    special: {
      mr: 'मंदिरातील मूर्ती पूर्वाभिमुख असून सिंहासनावर विराजमान आहे; डोळ्यात आणि नाभीमध्ये हिरे जडवलेले आहेत.',
      en: 'The east-facing idol sits on a throne with genuine diamonds embedded in the divine eyes and navel.',
    },
  },
  {
    id: 4,
    name: {
      mr: '४. श्री वरदविनायक (श्री क्षेत्र महड)',
      en: '4. Shri Varadvinayak (Mahad)',
    },
    district: {
      mr: 'रायगड (खोपोलीजवळ)',
      en: 'Raigad (Near Khopoli)',
    },
    vahana: {
      mr: 'मूषक',
      en: 'Mouse',
    },
    desc: {
      mr: 'येथे भाविकांच्या सर्व मनोकामना (वरद) पूर्ण होतात. मंदिराच्या गर्भगृहात १८९२ सालापासून अखंड नंदादीप तेवत आहे.',
      en: 'Bestower of boons and fulfilled desires (Varada). A sacred flame (Nandadeep) has remained continuously lit in the sanctum sanctorum since 1892.',
    },
    special: {
      mr: 'येथील मूर्ती स्वयंभू असून भाविकांना स्वतः गर्भगृहात जाऊन मूर्तीला स्पर्श करून पूजा करण्याची परवानगी आहे.',
      en: 'Devotees are uniquely permitted to personally enter the sanctum and offer holy touch prayers directly to the self-manifested idol.',
    },
  },
  {
    id: 5,
    name: {
      mr: '५. श्री चिंतामणी (श्री क्षेत्र थेऊर)',
      en: '5. Shri Chintamani (Theur)',
    },
    district: {
      mr: 'पुणे (मुळा-मुठा नदीसंगम)',
      en: 'Pune (Mula-Mutha Confluence)',
    },
    vahana: {
      mr: 'मूषक',
      en: 'Mouse',
    },
    desc: {
      mr: 'मनातील चिंता दूर करणारे चिंतामणी. महर्षी कपिलांचे चिंतामणी रत्न गणेशाने कपटी गणासुराकडून परत मिळवून दिले होते.',
      en: 'Dispeller of anxieties and worries (Chintamani). Lord Ganesha retrieved the wish-fulfilling jewel for sage Kapila from the greedy king Gana.',
    },
    special: {
      mr: 'श्रीमंत माधवराव पेशवे यांचे हे अत्यंत आवडते दैवत असून त्यांनी आपल्या आयुष्यातील शेवटचा काळ येथेच व्यतीत केला.',
      en: 'Beloved spiritual haven of Peshwa Madhavrao I, who renovated the complex and spent his final contemplative days here.',
    },
  },
  {
    id: 6,
    name: {
      mr: '६. श्री गिरिजात्मज (श्री क्षेत्र लेण्याद्री)',
      en: '6. Shri Girijatmaja (Lenyadri)',
    },
    district: {
      mr: 'जुन्नर, पुणे (कुकडी नदी)',
      en: 'Junnar, Pune (Kukadi River)',
    },
    vahana: {
      mr: 'मूषक',
      en: 'Mouse',
    },
    desc: {
      mr: 'माता पार्वतीने (गिरिजा) पुत्राच्या प्राप्तीसाठी येथे कठोर तप केले, म्हणून या रूपाला ‘गिरिजात्मज’ (गिरिजेचा पुत्र) म्हणतात.',
      en: 'Goddess Parvati (Girija) performed penance here to receive Lord Ganesha as her divine son (Girijatmaja).',
    },
    special: {
      mr: 'हे एकमेव मंदिर आहे जे डोंगरावरील बौद्ध लेण्यांच्या गुहेमध्ये वसलेले आहे; येथे पोहोचण्यासाठी ३०७ पायऱ्या चढाव्या लागतात.',
      en: 'The only Ashtavinayak temple nestled within ancient hillside caves; reached by ascending 307 stone steps carved into the cliff.',
    },
  },
  {
    id: 7,
    name: {
      mr: '७. श्री विघ्नेश्वर (श्री क्षेत्र ओझर)',
      en: '7. Shri Vighneshwar (Ozar)',
    },
    district: {
      mr: 'पुणे (कुकडी नदीकाठ)',
      en: 'Pune (Kukadi Riverbank)',
    },
    vahana: {
      mr: 'मूषक',
      en: 'Mouse',
    },
    desc: {
      mr: 'विघ्नासुर नावाच्या असुराचा पराभव करून संतांचे व ऋषींचे विघ्न हरण केले. असुराने शरण येऊन प्रार्थना केल्याने देवाचे नाव विघ्नेश्वर पडले.',
      en: 'Lord Ganesha subdued the obstinate demon Vighnasura to restore peace to sages. Accepting the demon\'s surrender, the Lord took the title Vighneshwara.',
    },
    special: {
      mr: 'मंदिराचा कळस सुवर्णमयी असून मंदिराभोवती भव्य तटबंदी आणि भव्य दीपमाळा आहेत.',
      en: 'Features a shimmering golden dome (Kalas) flanked by massive stone ramparts and majestic temple deepmalas (lamp towers).',
    },
  },
  {
    id: 8,
    name: {
      mr: '८. श्री महागणपती (श्री क्षेत्र रांजणगाव)',
      en: '8. Shri Mahaganapati (Ranjangaon)',
    },
    district: {
      mr: 'पुणे (पुणे-अहमदनगर रस्ता)',
      en: 'Pune (Pune-Nagar Highway)',
    },
    vahana: {
      mr: 'कमल / मूषक',
      en: 'Lotus / Mouse',
    },
    desc: {
      mr: 'भगवान शिवाने त्रिपुरासुराचा वध करण्यापूर्वी येथे महागणपतीची पूजा केली होती. हे गणेशाचे सर्वात शक्तिशाली आणि विराट रूप मानले जाते.',
      en: 'Lord Shiva invoked Mahaganapati here to conquer the invincible demon Tripurasura. Revered as the Lord\'s most mighty and cosmic manifestation.',
    },
    special: {
      mr: 'या मूर्तीला ‘दशमुखी’ (१० सोंडा आणि २० हात) स्वरूप मानले जाते; सूर्योदयाचे किरण थेट मूर्तीवर पडतात.',
      en: 'Envisioned in esoteric lore as Dashamukhi (10 trunks and 20 hands); morning sun rays illuminate the deity directly.',
    },
  },
];

export const DIVINE_SYMBOLS = [
  {
    icon: '🐘',
    title: {
      mr: 'मोठे मस्तक (Large Head)',
      en: 'Large Head (विशाल मस्तक)',
    },
    meaning: {
      mr: 'विशाल विचार (Think Big)',
      en: 'Think Big & Expand Intellect',
    },
    desc: {
      mr: 'बुद्धी, ज्ञान आणि दूरदृष्टीचे प्रतीक. नेहमी उच्च आणि सकारात्मक विचार करण्याची प्रेरणा देते.',
      en: 'Symbolizes vast wisdom, intellect, and foresight. Encourages thinking beyond personal ego and aspiring for noble goals.',
    },
  },
  {
    icon: '👂',
    title: {
      mr: 'सूपसारखे मोठे कान (Broad Ears)',
      en: 'Broad Ears (सूपकर्ण)',
    },
    meaning: {
      mr: 'उत्तम श्रवण (Listen More)',
      en: 'Listen Attentively',
    },
    desc: {
      mr: 'इतरांचे म्हणणे शांतपणे ऐकून घेणे आणि नको असलेल्या वाईट गोष्टी गाळून टाकणे.',
      en: 'Like a winnowing sieve, listen patiently to good counsel and filter out frivolous gossip or negativity.',
    },
  },
  {
    icon: '👄',
    title: {
      mr: 'लहान मुख (Small Mouth)',
      en: 'Small Mouth (मितभाषी मुख)',
    },
    meaning: {
      mr: 'मितभाषी (Speak Less)',
      en: 'Speak Less, Speak Sweetly',
    },
    desc: {
      mr: 'कमी आणि गोड बोला. वाणीवर संयम ठेवणे हाच आत्मिक उन्नतीचा खरा मार्ग आहे.',
      en: 'Teaches control over speech. Speaking measured, truthful, and benevolent words brings inner calm.',
    },
  },
  {
    icon: '👃',
    title: {
      mr: 'लांब व वक्र सोंड (Long Trunk)',
      en: 'Long Curved Trunk (वक्रतुंड)',
    },
    meaning: {
      mr: 'अनुकूलन व सामर्थ्य (High Efficiency)',
      en: 'Adaptability & Agility',
    },
    desc: {
      mr: 'अवघडात अवघड परिस्थितीतही शांत राहून योग्य मार्ग काढण्याची अफाट कार्यक्षमता.',
      en: 'Capable of uprooting a giant tree or picking up a needle. Symbolizes versatility and composure through life\'s storms.',
    },
  },
  {
    icon: '🪓',
    title: {
      mr: 'हातातील परशू व पाश (Axe & Rope)',
      en: 'Axe & Sacred Noose (परशू व पाश)',
    },
    meaning: {
      mr: 'आसक्ती तोडणे (Sever Attachments)',
      en: 'Cut Bonds of Illusion',
    },
    desc: {
      mr: 'अहंकार व संसारातील व्यर्थ बंधने तोडून सत्याच्या आणि भगवंताच्या मार्गावर चालणे.',
      en: 'The axe severs ego and material delusion; the noose gently draws the spiritual seeker toward truth.',
    },
  },
  {
    icon: '🦷',
    title: {
      mr: 'एकदंत (Broken Tusk)',
      en: 'Single Tusk (एकदंत)',
    },
    meaning: {
      mr: 'त्याग व निष्ठा (Sacrifice for Knowledge)',
      en: 'Sacrifice for Knowledge',
    },
    desc: {
      mr: 'महाभारत लिहिण्यासाठी स्वतःचा दात अर्पण केला. ज्ञानासाठी आणि कर्तव्यासाठी कोणताही त्याग करण्याची तयारी.',
      en: 'Broke His own tusk without hesitation to pen the sacred epic Mahabharata, teaching total dedication to duty.',
    },
  },
  {
    icon: '🍲',
    title: {
      mr: 'विशाल उदर (Large Belly)',
      en: 'Expansive Belly (लंबोदर)',
    },
    meaning: {
      mr: 'सुख-दुःख पचवणे (Digest All Experiences)',
      en: 'Digest All Experiences with Grace',
    },
    desc: {
      mr: 'जीवनातील सुख आणि दुःख, स्तुती आणि निंदा समान भावनेने पचवण्याची सहनशीलता.',
      en: 'Contained the entire cosmos; inspires maintaining emotional equilibrium amidst triumphs and adversities.',
    },
  },
  {
    icon: '🍬',
    title: {
      mr: 'हातातील मोदक (Modak)',
      en: 'Sweet Modak (मोदक)',
    },
    meaning: {
      mr: 'साधनेचे गोड फळ (Sweet Reward of Virtue)',
      en: 'Sweet Reward of Spiritual Practice',
    },
    desc: {
      mr: 'सत्कर्म आणि भक्तीचे अंतिम फळ नेहमी मोदकासारखे गोड आणि तृप्ती देणारे असते.',
      en: 'Hidden sweetness enclosed within an outer shell. Signifies the inner bliss discovered after disciplined effort.',
    },
  },
  {
    icon: '🐁',
    title: {
      mr: 'मूषक वाहन (Tiny Mouse)',
      en: 'Little Mouse Mount (मूषक)',
    },
    meaning: {
      mr: 'इच्छांवर नियंत्रण (Control Over Desires)',
      en: 'Mastering Restless Desires',
    },
    desc: {
      mr: 'मूषक हा चंचल वासनेचे प्रतीक आहे. बाप्पा त्यावर स्वार होऊन चंचल मनावर विजय मिळवण्याचा संदेश देतात.',
      en: 'A mouse gnaws incessantly in the dark. Lord Ganesha riding upon it signifies conquering the wandering mind.',
    },
  },
];

export const DEFAULT_DAILY_SCHEDULE = [
  {
    id: 'sch-1',
    time: { mr: 'सकाळी ०६:००', en: '06:00 AM' },
    title: { mr: 'काकड आरती व भूपाळी', en: 'Kakad Aarti & Morning Hymns' },
    icon: '🌅',
    desc: {
      mr: 'बाप्पाची मंगल प्रभात व सुमधूर भूपाळी गायन.',
      en: 'Auspicious dawn greeting and melodious awakening prayers.',
    },
  },
  {
    id: 'sch-2',
    time: { mr: 'सकाळी ०८:३०', en: '08:30 AM' },
    title: { mr: 'अभिषेक, पंचामृत स्नान व नित्य पूजा', en: 'Abhishek, Panchamrut Snan & Pooja' },
    icon: '🪔',
    desc: {
      mr: 'वेदमंत्रांच्या जयघोषात मुख्य मूर्तीचा पवित्र अभिषेक.',
      en: 'Sacred Vedic chanting accompanying ritual deity purification.',
    },
  },
  {
    id: 'sch-3',
    time: { mr: 'दुपारी १२:१५', en: '12:15 PM' },
    title: { mr: 'दुपारची नैवेद्य महाआरती', en: 'Midday Naivedya Maha Aarti' },
    icon: '🔔',
    desc: {
      mr: '२१ मोदक व पंचपक्वान्न नैवेद्य अर्पण.',
      en: 'Offering of 21 modaks and traditional feast delights.',
    },
  },
  {
    id: 'sch-4',
    time: { mr: 'दुपारी १२:३० ते ०३:००', en: '12:30 PM - 03:00 PM' },
    title: { mr: 'सार्वजनिक महाप्रसाद (अन्नदान)', en: 'Public Maha-Prasad (Annadaan)' },
    icon: '🍲',
    desc: {
      mr: 'सर्व भाविकांसाठी महाप्रसाद भोजन व्यवस्था.',
      en: 'Free wholesome sanctified meal served to all visiting devotees.',
    },
  },
  {
    id: 'sch-5',
    time: { mr: 'सायंकाळी ०७:३०', en: '07:30 PM' },
    title: { mr: 'मुख्य संध्या महाआरती व धूपारती', en: 'Grand Evening Sandhya Maha Aarti' },
    icon: '🕯️',
    desc: {
      mr: 'दिव्यांच्या लखलखाटात आणि ढोल-ताशांच्या गजरात महाआरती.',
      en: 'Magnificent prayer resonance with holy lamps, conch, and cymbals.',
    },
  },
  {
    id: 'sch-6',
    time: { mr: 'रात्री ०८:३० ते १०:३०', en: '08:30 PM - 10:30 PM' },
    title: { mr: 'रात्रीचा महाप्रसाद वाटप', en: 'Evening Prasadam Distribution' },
    icon: '🍛',
    desc: {
      mr: 'सायंकाळच्या दर्शनार्थी भाविकांसाठी प्रसाद वितरण.',
      en: 'Evening prasad served for nighttime pandal visitors.',
    },
  },
  {
    id: 'sch-7',
    time: { mr: 'रात्री १०:००', en: '10:00 PM' },
    title: { mr: 'शेजारती व मूक दर्शन', en: 'Shej Aarti & Silent Darshan' },
    icon: '🌙',
    desc: {
      mr: 'दिवसाच्या सांगतेची शांत आणि भावपूर्ण शेजारती.',
      en: 'Peaceful night lullaby hymn concluding the day\'s festivities.',
    },
  },
];

export const SPECIAL_FESTIVAL_EVENTS = [
  {
    day: { mr: 'दिवस १ (गणेश चतुर्थी)', en: 'Day 1 (Ganesh Chaturthi)' },
    title: { mr: 'श्रींची प्राणप्रतिष्ठापना व आगमन सोहळा', en: 'Prana Pratishthapana & Welcoming Procession' },
    desc: { mr: 'पारंपरिक वाद्यांच्या गजरात बाप्पाचे वाजत-गाजत आगमन.', en: 'Grand traditional musical reception and consecration ceremony.' },
  },
  {
    day: { mr: 'दिवस ३', en: 'Day 3' },
    title: { mr: 'महिला हळदी-कुंकू व अथर्वशीर्ष पठण', en: 'Haldi-Kumkum & Atharvashirsha Chanting' },
    desc: { mr: 'सामूहिक १०८ वेळा श्री गणपती अथर्वशीर्ष आवर्तन.', en: 'Congregational 108 recitations of Shri Ganapati Atharvashirsha.' },
  },
  {
    day: { mr: 'दिवस ५', en: 'Day 5' },
    title: { mr: 'गौरी आगमन व पूजन', en: 'Mata Gauri Arrival & Pooja' },
    desc: { mr: 'माता गौरीचे सवाद्य आगमन, सजावट व पारंपरिक गाणी.', en: 'Devotional reception of Goddess Gauri with ornate folk customs.' },
  },
  {
    day: { mr: 'दिवस ७', en: 'Day 7' },
    title: { mr: 'भव्य भजन संध्या व कीर्तन महोत्सव', en: 'Bhajan Sandhya & Kirtan Mahotsav' },
    desc: { mr: 'प्रसिद्ध वारकरी बुवांचे संगीतमय कीर्तन व भजन.', en: 'Soul-stirring classical kirtan by renowned spiritual singers.' },
  },
  {
    day: { mr: 'दिवस ९', en: 'Day 9' },
    title: { mr: 'सत्यविनायक महापूजा व ५६ भोग', en: 'Satyavinayak Mahapooja & 56 Bhog' },
    desc: { mr: 'अखंड ५६ प्रकारच्या मिष्ठांनांचा छप्पन भोग नैवेद्य.', en: '56 sacred delicacies offered in devotion for welfare.' },
  },
  {
    day: { mr: 'दिवस १० (अनंत चतुर्दशी)', en: 'Day 10 (Anant Chaturdashi)' },
    title: { mr: 'महाविसर्जन मिरवणूक व निरोप', en: 'Grand Visarjan Farewell Procession' },
    desc: { mr: 'गुलाल, फुले आणि टाळ-मृदुंगाच्या गजरात भावपूर्ण विसर्जन सोहळा.', en: 'Grand musical send-off showered in flowers with chants of Bappa Morya!' },
  },
];

export const DEFAULT_SOCIAL_INITIATIVES = [
  {
    id: 'init-1',
    title: {
      mr: 'भव्य रक्तदान शिबिर (Blood Donation Camp)',
      en: 'Grand Blood Donation Camp',
    },
    stats: {
      mr: '२५०+ बाटल्या रक्त संकलन',
      en: '250+ Units of Blood Collected',
    },
    desc: {
      mr: 'दरवर्षी गणेशोत्सवाच्या ५ व्या दिवशी स्थानिक शासकीय रुग्णालयांच्या सहकार्याने आयोजित.',
      en: 'Organized annually on the 5th day of the festival in partnership with local civic hospitals.',
    },
    iconName: 'Droplet',
    tag: {
      mr: 'आरोग्य सेवा',
      en: 'Healthcare Seva',
    },
    color: 'border-rose-500/40 bg-rose-950/30 text-rose-300',
  },
  {
    id: 'init-2',
    title: {
      mr: 'दैनिक महाप्रसाद वाटप (Maha Prasad)',
      en: 'Daily Community Maha-Prasad (Annadaan)',
    },
    stats: {
      mr: '१,५००+ दररोज थाळ्या',
      en: '1,500+ Daily Meals Served',
    },
    desc: {
      mr: 'मंडळात येणाऱ्या प्रत्येक भाविकासाठी शुद्ध, सात्विक आणि तृप्त करणारा महाप्रसाद विनामूल्य.',
      en: 'Providing wholesome, sanctified, and delicious meals free of charge to all visiting devotees.',
    },
    iconName: 'Utensils',
    tag: {
      mr: 'अन्नदान सेवा',
      en: 'Annadaan Seva',
    },
    color: 'border-amber-500/40 bg-amber-950/30 text-amber-300',
  },
  {
    id: 'init-3',
    title: {
      mr: 'गुणवंत विद्यार्थी सत्कार व शैक्षणिक मदत',
      en: 'Meritorious Student Scholarships & Book Drive',
    },
    stats: {
      mr: '५० गरजू विद्यार्थ्यांना शिष्यवृत्ती',
      en: '50+ Underprivileged Students Supported',
    },
    desc: {
      mr: 'परिसरातील होतकरू विद्यार्थ्यांना वह्या, पुस्तके व शालेय साहित्य वाटप उपक्रम.',
      en: 'Distributing school kits, textbooks, uniforms, and educational scholarships to deserving local youth.',
    },
    iconName: 'GraduationCap',
    tag: {
      mr: 'शैक्षणिक सेवा',
      en: 'Education Seva',
    },
    color: 'border-orange-500/40 bg-orange-950/30 text-orange-300',
  },
  {
    id: 'init-4',
    title: {
      mr: 'बाल संस्कार व सांस्कृतिक स्पर्धा',
      en: 'Cultural Competitions & Children\'s Talent Showcase',
    },
    stats: {
      mr: '४००+ बाल कलाकार सहभागी',
      en: '400+ Young Participants',
    },
    desc: {
      mr: 'चित्रकला, वकृत्व, श्लोक पठण व पारंपरिक भजन स्पर्धांचे आयोजन करून कलागुणांना प्रोत्साहन.',
      en: 'Encouraging young talent through drawing, shloka chanting, elocution, and traditional music contests.',
    },
    iconName: 'Award',
    tag: {
      mr: 'संस्कृती संवर्धन',
      en: 'Culture & Heritage',
    },
    color: 'border-red-500/40 bg-red-950/30 text-red-300',
  },
];

export const BASE_TICKER_ITEMS = {
  mr: [
    { id: 'mantra-1', icon: '🚩', text: '॥ गणपती बाप्पा मोरया, मंगल मूर्ती मोरया! ॥' },
    { id: 'aarti-time', icon: '🔔', text: 'दैनिक संध्या महाआरती: दररोज सायंकाळी ७:३० वाजता' },
    { id: 'prasad-time', icon: '🍲', text: 'महाप्रसाद वाटप: दुपारी १२:३० ते ३:०० आणि रात्री ८:३० ते १०:३०' },
    { id: 'diya-seva', icon: '🪔', text: 'अखंड दीप प्रज्वलन सेवा: नोंदणी मंडप कार्यालयात सुरू आहे' },
    { id: 'pushpa-seva', icon: '🌸', text: 'पुष्पवृष्टी व २१ मोदक नैवेद्य अर्पण: सर्व भाविकांचे हार्दिक स्वागत!' },
  ],
  en: [
    { id: 'mantra-1', icon: '🚩', text: '|| Ganpati Bappa Morya, Mangal Murti Morya! ||' },
    { id: 'aarti-time', icon: '🔔', text: 'Daily Evening Maha Aarti: Every evening at 07:30 PM' },
    { id: 'prasad-time', icon: '🍲', text: 'Maha-Prasad Timings: 12:30 PM - 03:00 PM & 08:30 PM - 10:30 PM' },
    { id: 'diya-seva', icon: '🪔', text: 'Akhanda Diya Devotion Service: Registrations open at the counter' },
    { id: 'pushpa-seva', icon: '🌸', text: 'Flower Shower & 21 Modak Offerings: Warm welcome to all devotees!' },
  ],
};

export const SEVA_CATEGORIES = [
  { id: 'general', mr: 'सर्वसाधारण देणगी', en: 'General Donation', icon: '🪙' },
  { id: 'prasad', mr: 'महाप्रसाद सेवा', en: 'Maha-Prasad Seva', icon: '🍛' },
  { id: 'aarti', mr: 'दैनिक महाआरती', en: 'Daily Maha Aarti', icon: '🔔' },
  { id: 'modak', mr: 'मोदक नैवेद्य अर्पण', en: 'Modak Offering', icon: '🍬' },
  { id: 'deep', mr: 'अखंड दीप & धूप सेवा', en: 'Sacred Flame & Dhoop', icon: '🪔' },
  { id: 'flower', mr: 'पुष्पवृष्टी व सजावट', en: 'Flower Shower & Decor', icon: '🌸' },
];

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('ganpati_language') || 'mr';
  });

  const changeLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem('ganpati_language', newLang);
  };

  const toggleLanguage = () => {
    const nextLang = lang === 'mr' ? 'en' : 'mr';
    changeLanguage(nextLang);
  };

  const t = (key) => {
    if (TRANSLATIONS[lang] && TRANSLATIONS[lang][key] !== undefined) {
      return TRANSLATIONS[lang][key];
    }
    // Fallback to Marathi or English or raw key
    return TRANSLATIONS.mr?.[key] || TRANSLATIONS.en?.[key] || key;
  };

  // Helper to pick localized value from object { mr: '...', en: '...' } or string
  const pick = (val) => {
    if (!val) return '';
    if (typeof val === 'string') return val;
    return val[lang] || val.mr || val.en || '';
  };

  return (
    <LanguageContext.Provider
      value={{
        lang,
        setLanguage: changeLanguage,
        toggleLanguage,
        t,
        pick,
        isMarathi: lang === 'mr',
        isEnglish: lang === 'en',
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;
